<?php
require_once __DIR__.'/../includes/functions.php'; require_login(['admin']);
$type=$_GET['type'] ?? 'mahasiswa';
$configs=[
'mahasiswa'=>['title'=>'Mahasiswa','table'=>'mahasiswa','pk'=>'id','fields'=>['npm'=>'NPM','nama'=>'Nama','jk'=>'Jenis Kelamin (L/P)','alamat'=>'Alamat','prodi'=>'Program Studi','angkatan'=>'Angkatan'],'list'=>'SELECT * FROM mahasiswa ORDER BY nama'],
'dosen'=>['title'=>'Dosen','table'=>'dosen','pk'=>'id','fields'=>['nidn'=>'NIDN','nama'=>'Nama'],'list'=>'SELECT * FROM dosen ORDER BY nama'],
'mata_kuliah'=>['title'=>'Mata Kuliah','table'=>'mata_kuliah','pk'=>'id','fields'=>['kode'=>'Kode','nama'=>'Nama','sks'=>'SKS'],'list'=>'SELECT * FROM mata_kuliah ORDER BY kode'],
'tahun_akademik'=>['title'=>'Tahun Akademik','table'=>'tahun_akademik','pk'=>'id','fields'=>['tahun'=>'Tahun (mis. 2025/2026)','semester'=>'Semester (Ganjil/Genap)','status'=>'Status (Aktif/Nonaktif)'],'list'=>'SELECT * FROM tahun_akademik ORDER BY tahun DESC'],
'kelas'=>['title'=>'Kelas','table'=>'kelas','pk'=>'id','fields'=>['id_mk'=>'ID Mata Kuliah','id_dosen'=>'ID Dosen','id_tahun_akademik'=>'ID Tahun Akademik','nama_kelas'=>'Nama Kelas','kapasitas'=>'Kapasitas'],'list'=>'SELECT k.*,m.kode,m.nama mk,d.nama dosen,t.tahun,t.semester FROM kelas k JOIN mata_kuliah m ON m.id=k.id_mk LEFT JOIN dosen d ON d.id=k.id_dosen JOIN tahun_akademik t ON t.id=k.id_tahun_akademik ORDER BY k.id DESC'],
'users'=>['title'=>'Pengguna','table'=>'users','pk'=>'id','fields'=>['username'=>'Username','password'=>'Password (kosongkan saat edit)','role'=>'Peran (admin/dosen/mahasiswa)','is_active'=>'Aktif (1/0)'],'list'=>'SELECT id,username,role,is_active,created_at FROM users ORDER BY id DESC'],
]; if(!isset($configs[$type])) exit('Data master tidak ditemukan.'); $c=$configs[$type]; $pdo=db(); $id=(int)($_GET['id']??0);
if(isset($_GET['delete']) && $id){ if(!hash_equals(csrf(),$_GET['csrf']??'')) exit('Permintaan tidak valid.'); $pdo->prepare("DELETE FROM {$c['table']} WHERE {$c['pk']}=?")->execute([$id]); flash('success','Data dihapus.'); redirect("admin/master.php?type=$type"); }
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf(); $data=[]; foreach($c['fields'] as $field=>$label){$value=trim($_POST[$field]??''); if($field==='password' && $value==='')continue; $data[$field]=$field==='password'?password_hash($value,PASSWORD_DEFAULT):$value;} try { if($id){$set=implode(',',array_map(fn($f)=>"$f=?",array_keys($data)));$pdo->prepare("UPDATE {$c['table']} SET $set WHERE {$c['pk']}=?")->execute([...array_values($data),$id]);} else {$fields=array_keys($data);$pdo->prepare("INSERT INTO {$c['table']} (".implode(',',$fields).") VALUES (".implode(',',array_fill(0,count($fields),'?')).")")->execute(array_values($data));} flash('success','Data berhasil disimpan.');redirect("admin/master.php?type=$type");}catch(PDOException $e){flash('error','Gagal menyimpan: '.$e->getMessage());}}
$edit=$id?$pdo->prepare("SELECT * FROM {$c['table']} WHERE {$c['pk']}=?"):null; if($edit){$edit->execute([$id]);$edit=$edit->fetch()?:[];} $rows=$pdo->query($c['list'])->fetchAll(); $page_title='CRUD '.$c['title']; require_once __DIR__.'/../includes/header.php'; ?>
<div class="d-flex justify-content-between mb-4"><div><h3><?=$c['title']?></h3><p class="text-secondary mb-0">Kelola data <?=$c['title']?>.</p></div><a class="btn btn-primary" href="?type=<?=$type?>&id=0"><i class="bi bi-plus-lg"></i> Tambah</a></div>
<?php if($id || isset($_GET['id'])): ?><div class="card p-4 mb-4"><h5><?= $id?'Edit':'Tambah' ?> <?=$c['title']?></h5><form method="post" class="row g-3"><?=csrf_field()?><?php foreach($c['fields'] as $f=>$label):?><div class="col-md-6"><label class="form-label"><?=e($label)?></label><?php if($f==='alamat'):?><textarea class="form-control" name="<?=$f?>"><?=e($edit[$f]??'')?></textarea><?php else:?><input class="form-control" name="<?=$f?>" value="<?=e($f==='password'?'':($edit[$f]??''))?>" <?= $f==='password'?'type="password"':'required' ?>></div><?php endif?></div><?php endforeach?><div><button class="btn btn-primary">Simpan</button><a class="btn btn-light" href="?type=<?=$type?>">Batal</a></div></form></div><?php endif?>
<div class="card p-4"><div class="table-responsive"><table class="table datatable"><thead><tr><?php foreach($c['fields'] as $f=>$l):?><th><?=e(strtok($l,'('))?></th><?php endforeach?><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><?php foreach($c['fields'] as $f=>$l):?><td><?=e($f==='password'?'••••••':($row[$f]??($f==='id_mk'?($row['kode'].' — '.$row['mk']):'')))?></td><?php endforeach?><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="?type=<?=$type?>&id=<?=$row['id']?>">Edit</a><a onclick="return confirm('Hapus data ini?')" class="btn btn-sm btn-outline-danger" href="?type=<?=$type?>&id=<?=$row['id']?>&delete=1&csrf=<?=csrf() ?>">Hapus</a></td></tr><?php endforeach?></tbody></table></div></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
