CREATE DATABASE IF NOT EXISTS siakad CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE siakad;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS nilai,krs,kelas,mata_kuliah,tahun_akademik,mahasiswa,dosen,users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role ENUM('admin','dosen','mahasiswa') NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE mahasiswa (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL UNIQUE,npm VARCHAR(20) NOT NULL UNIQUE,nama VARCHAR(100) NOT NULL,jk ENUM('L','P') NOT NULL,alamat TEXT NULL,prodi VARCHAR(100) NOT NULL,angkatan YEAR NOT NULL,CONSTRAINT fk_mhs_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE dosen (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL UNIQUE,nidn VARCHAR(20) NOT NULL UNIQUE,nama VARCHAR(100) NOT NULL,CONSTRAINT fk_dosen_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE mata_kuliah (id INT AUTO_INCREMENT PRIMARY KEY,kode VARCHAR(15) NOT NULL UNIQUE,nama VARCHAR(100) NOT NULL,sks TINYINT UNSIGNED NOT NULL) ENGINE=InnoDB;
CREATE TABLE tahun_akademik (id INT AUTO_INCREMENT PRIMARY KEY,tahun VARCHAR(9) NOT NULL,semester ENUM('Ganjil','Genap') NOT NULL,status ENUM('Aktif','Nonaktif') NOT NULL DEFAULT 'Nonaktif',UNIQUE(tahun,semester)) ENGINE=InnoDB;
CREATE TABLE kelas (id INT AUTO_INCREMENT PRIMARY KEY,id_mk INT NOT NULL,id_dosen INT NULL,id_tahun_akademik INT NOT NULL,nama_kelas VARCHAR(20) NOT NULL,kapasitas SMALLINT UNSIGNED DEFAULT 40,CONSTRAINT fk_kelas_mk FOREIGN KEY(id_mk) REFERENCES mata_kuliah(id) ON DELETE CASCADE,CONSTRAINT fk_kelas_dosen FOREIGN KEY(id_dosen) REFERENCES dosen(id) ON DELETE SET NULL,CONSTRAINT fk_kelas_ta FOREIGN KEY(id_tahun_akademik) REFERENCES tahun_akademik(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE krs (id INT AUTO_INCREMENT PRIMARY KEY,id_mahasiswa INT NOT NULL,id_mk INT NOT NULL,id_kelas INT NOT NULL,id_tahun_akademik INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(id_mahasiswa,id_kelas,id_tahun_akademik),CONSTRAINT fk_krs_mhs FOREIGN KEY(id_mahasiswa) REFERENCES mahasiswa(id) ON DELETE CASCADE,CONSTRAINT fk_krs_mk FOREIGN KEY(id_mk) REFERENCES mata_kuliah(id) ON DELETE RESTRICT,CONSTRAINT fk_krs_kelas FOREIGN KEY(id_kelas) REFERENCES kelas(id) ON DELETE RESTRICT,CONSTRAINT fk_krs_ta FOREIGN KEY(id_tahun_akademik) REFERENCES tahun_akademik(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE nilai (id INT AUTO_INCREMENT PRIMARY KEY,id_krs INT NOT NULL UNIQUE,tugas DECIMAL(5,2) NOT NULL,uts DECIMAL(5,2) NOT NULL,uas DECIMAL(5,2) NOT NULL,nilai_akhir DECIMAL(5,2) NOT NULL,nilai_huruf VARCHAR(2) NOT NULL,bobot DECIMAL(3,1) NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_nilai_krs FOREIGN KEY(id_krs) REFERENCES krs(id) ON DELETE CASCADE) ENGINE=InnoDB;

-- Jalankan password_setup.php sekali setelah import untuk membuat hash password demo.
INSERT INTO users(username,password,role) VALUES ('admin','!', 'admin');
INSERT INTO tahun_akademik(tahun,semester,status) VALUES ('2025/2026','Ganjil','Nonaktif'),('2025/2026','Genap','Aktif');
INSERT INTO mata_kuliah(kode,nama,sks) VALUES ('IF101','Algoritma dan Pemrograman',3),('IF102','Basis Data',3),('IF103','Pemrograman Web',3),('IF104','Struktur Data',3),('IF105','Jaringan Komputer',3),('IF106','Sistem Operasi',3),('IF107','Matematika Diskrit',2),('IF108','Kalkulus',2),('IF109','Bahasa Inggris',2),('IF110','Pancasila',2),('IF111','Kewirausahaan',2),('IF112','Rekayasa Perangkat Lunak',3),('IF113','Kecerdasan Buatan',3),('IF114','Keamanan Informasi',3),('IF115','Statistika',2);
INSERT INTO mahasiswa(npm,nama,jk,alamat,prodi,angkatan) VALUES ('2301001','Andi Pratama','L','Bandar Lampung','Informatika',2023),('2301002','Budi Santoso','L','Bandar Lampung','Informatika',2023),('2301003','Citra Lestari','P','Metro','Informatika',2023),('2301004','Dinda Putri','P','Bandar Lampung','Informatika',2023),('2301005','Eko Saputra','L','Metro','Informatika',2023),('2301006','Fajar Ramadhan','L','Bandar Lampung','Informatika',2023),('2301007','Gita Anggraini','P','Metro','Informatika',2023),('2301008','Hana Sari','P','Bandar Lampung','Informatika',2023),('2301009','Indra Kurniawan','L','Metro','Informatika',2023),('2301010','Joko Susilo','L','Bandar Lampung','Informatika',2023),('2301011','Kartika Dewi','P','Metro','Informatika',2023),('2301012','Lina Marlina','P','Bandar Lampung','Informatika',2023),('2301013','Maya Sari','P','Metro','Informatika',2023),('2301014','Nanda Prakoso','L','Bandar Lampung','Informatika',2023),('2301015','Oki Setiawan','L','Metro','Informatika',2023),('2301016','Putri Amelia','P','Bandar Lampung','Informatika',2023),('2301017','Rian Hidayat','L','Metro','Informatika',2023),('2301018','Siti Nurhaliza','P','Bandar Lampung','Informatika',2023),('2301019','Tono Wijaya','L','Metro','Informatika',2023),('2301020','Vina Safitri','P','Bandar Lampung','Informatika',2023);
INSERT INTO dosen(nidn,nama) VALUES ('001','Dr. Ahmad Fauzi, M.Kom. '),('002','Dr. Budi Hartono, M.Kom.'),('003','Citra Dewi, M.Kom.'),('004','Dedi Irawan, M.Kom.'),('005','Eka Fitriani, M.Kom.'),('006','Fajar Nugroho, M.Kom.'),('007','Gina Lestari, M.Kom.'),('008','Hendra Saputra, M.Kom.');
INSERT INTO kelas(id_mk,id_dosen,id_tahun_akademik,nama_kelas,kapasitas) VALUES (1,1,2,'IF-3A',45),(2,2,2,'IF-3A',45),(3,3,2,'IF-3A',45),(4,4,2,'IF-3A',45),(5,5,2,'IF-3A',45),(6,6,2,'IF-3A',45),(7,7,2,'IF-3A',45),(8,8,2,'IF-3A',45),(9,1,2,'IF-3A',45),(10,2,2,'IF-3A',45),(11,3,2,'IF-3A',45),(12,4,2,'IF-3A',45),(13,5,2,'IF-3A',45),(14,6,2,'IF-3A',45),(15,7,2,'IF-3A',45);
-- Tepat 100 KRS dan 100 nilai dummy: 20 mahasiswa x 5 mata kuliah.
INSERT INTO krs(id_mahasiswa,id_mk,id_kelas,id_tahun_akademik) SELECT m.id,k.id,k.id,2 FROM mahasiswa m JOIN kelas k ON k.id BETWEEN 1 AND 5;
INSERT INTO nilai(id_krs,tugas,uts,uas,nilai_akhir,nilai_huruf,bobot) SELECT id,80,80,80,80,'AB',3.5 FROM krs;
